#!/bin/sh

# wait up to 10 seconds for Vault to elect a leader.
# return 1 on failure.
assert_ready() {
    for _ in $(seq 0 10); do
        curl -s --fail -o /dev/null \
            "http://127.0.0.1:8200/v1/sys/leader"
        [ $? -eq 0 ] && exit 0
        sleep 1
    done || (echo "failed to get a leader" && exit 1)
}

# ---------------------------------------------------
# parse arguments

while true; do
    case $1 in
        ready ) assert_ready; break;;
        *)
            echo "requires assertion argument"
            exit 1
            break;;
    esac
done
